### ISSUE TITLE
No way to unload the plugin

### ISSUE THREAD

**Issue by codearachnid** [mattyza/starter-plugin#1]
Might I suggest that you add a hook to allow dynamic unloading of your plugin programatically? Instead of directly calling `Starter_Plugin();` use `add_action( 'plugins_loaded', 'Starter_Plugin' );` instead.

Also since this is your starter plugin boilerplate it might be a good idea to create a simple prefix that could be globally replaced (similar to how the _s project works).

**Comment by cmwwebfx** [comment]
@mattyza Is this something that can be taken care please. It has been assigned enhancement since May 2014. 
Prefixing as per comment of @codearachnid is a superb idea as it will allow for simple search replace.
